(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 336,
	height: 280,
	fps: 22,
	color: "#000000",
	manifest: [
		{src:"GreenCard.jpg", id:"GreenCard"},
		{src:"bluebox.png", id:"Logo_neu"}
	]
};



// symbols:



(lib.GreenCard = function() {
	this.initialize(img.GreenCard);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,102,66);


(lib.Logo_neu = function() {
	this.initialize(img.Logo_neu);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,48,41);


(lib.PNG_Logo = function() {
	this.initialize();

	// Ebene 1
	this.instance = new lib.Logo_neu();
	this.instance.setTransform(40,0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(40,0,48,41);


(lib.nnter = function() {
	this.initialize();

	// Ebene 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACrBoQgdgBgRgVQgSgVABghQABgfASgVQATgUAdABQAeABAQATQAQAUgBAfIAAAFIhhgCIgBADIAAADQgBAXALAOQALANASABQAPAAAMgHQAMgIAJgQIAKAGQgKAVgQAKQgQAKgUAAIgCAAgACVgTQgIANgCAYIA4ABQAGAAACgBQACgCABgGQAAgSgIgMQgIgKgPgBIgBAAQgQAAgJAMgAD8BlIAAgNIAOAAQAGAAACgCQACgCAAgHIADhZQAAgHgDgCQgDgDgMAAIgJAAIAAgMIA0gCIgBAoQAIgTAMgLQALgKAPAAQAMAAAHAIQAIAHgBALQAAAJgFADQgFAEgIAAQgIAAgFgEQgEgDAAgIQAAgEACgEIAEgFIgBAAQgQgBgMAWQgMASgBAfIgBAgQAAAHACACQACACAGABIASABIAAAMgAArBkQgTAAgIgJQgHgJABgYIAChXIgWgBIAAgMQARgBAKgPQALgQACgdIAMABIgBA8IArABIAAAOIgtgBIgCBUQgBAPAEAFQAEAGAKAAQAMABAGgKQAHgKABgVIALAAIAAAEQgBAbgMAOQgMANgWAAIgBAAgAhiBcIABgNIANAAQAGAAACgCQACgCAAgHIAChFQAAgNgHgIQgHgIgNAAQgUgBgJANQgKAMgBAXIgBAxQAAAHACACQABACAHABIAMABIAAAMIhJgBIABgNIAMAAQAHAAACgCQABgCAAgHIADhZQAAgHgDgDQgDgDgKAAIgEABIgFgBIAAgMIAzgCIAAAdQAKgOAMgHQAMgHAPABQAWAAAMANQALANAAAWIgCBFQAAAHACACQABACAHABIAMAAIAAANgAkZBXIAAgNIANAAQAGAAACgCQACgCAAgHIAChFQABgNgIgIQgHgIgNAAQgTgBgKANQgKAMAAAXIgCAxQAAAHACACQACACAGABIANABIgBAMIhIgBIAAgNIANAAQAGAAACgCQACgCAAgHIAChZQAAgHgCgDQgEgDgKAAIgEABIgFgBIAAgMIA0gCIgBAdQALgOAMgHQALgHAQABQAVAAAMANQAMANgBAXIgCBEQAAAHACACQACACAGABIANAAIgBANg");
	this.shape.setTransform(-2,-6.4);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-39.5,-16.8,75.2,20.9);


(lib.Klassiker_mc = function() {
	this.initialize();

	// Ebene 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AihB2IgEgIIgCgIIgBAJIgCAJIgOA/IgTAAIAfiGIAmBRIACAHIAFALIAFgPIACgDIAlhRIAfCGIgTAAIgPg/IgBgJIgBgJIgCAJIgEAJIghBEgAHDCuQgMgMAAgVQAAgTAMgMQAMgNAUAAQAUAAALALQALAMAAAVIAAADIhCAAQAAAMAHAGQAGAHAKAAQAJAAAGgEQAHgEAEgJIAQAJQgHANgKAGQgKAHgOgBQgUAAgMgMgAHUB1QgGAFgCAJIAtAAQgBgJgFgFQgGgEgKAAQgKAAgFAEgACyCuQgMgMAAgVQAAgTANgMQAMgNATAAQAUAAALALQAMAMAAAVIAAADIhDAAQABAMAGAGQAGAHALAAQAJAAAGgEQAGgEAFgJIAQAJQgHANgLAGQgKAHgOgBQgUAAgMgMgADDB1QgFAFgDAJIAuAAQgBgJgGgFQgGgEgKAAQgJAAgGAEgABHCvQgKgMAAgWQAAgTALgNQAKgMARAAQAKAAAHAEQAHAEAEAIIAAhCIATAAIAACIIgTAAIAAgLQgFAIgHADQgHADgJAAQgRABgLgMgABXB5QgGAIAAANQAAANAGAHQAGAIALgBQAKABAHgJQAGgHAAgNQAAgNgGgHQgGgHgLgBQgKABgHAHgAgOC3QgJgDgGgHQgHgGgDgIQgEgJAAgJQAAgJAEgIQADgIAHgGQAGgHAIgDQAJgDAHAAQAJAAAJADQAIAEAHAGQAGAHAEAHQADAIAAAJQAAAJgDAJQgEAIgGAGQgHAHgIADQgJADgJAAQgHAAgIgDgAgPB6QgIAIAAALQAAAMAIAIQAHAJAJgBQALABAHgJQAIgIAAgMQAAgLgIgIQgHgIgLAAQgJAAgHAIgAmXCuQgMgMAAgVQAAgTAMgMQAMgNAUAAQAUAAALALQALAMAAAVIAAADIhCAAQAAAMAHAGQAGAHAKAAQAJAAAGgEQAHgEAEgJIAQAJQgHANgKAGQgKAHgOgBQgUAAgMgMgAmGB1QgGAFgCAJIAtAAQgBgJgFgFQgGgEgKAAQgKAAgFAEgAoCCvQgKgMAAgWQAAgTAKgNQALgMAQAAQAKAAAIAEQAHAEADAIIAAhCIATAAIAACIIgTAAIAAgLQgFAIgHADQgGADgJAAQgSABgKgMgAnyB5QgGAIAAANQAAANAGAHQAGAIALgBQAKABAGgJQAHgHAAgNQAAgNgGgHQgGgHgLgBQgLABgGAHgAGQC3IAAgrQAAgQgEgFQgEgGgKAAQgHAAgFACQgFADgDAEIgDAIIgBAPIAAAmIgTAAIAAhUIASAAIAAAOQAGgJAHgDQAIgEALAAQAJAAAHADQAHACADAGIADAIIABAQIAAAzgAEQC3IAAhUIAUAAIAAAOQADgIAFgEQAFgEAHAAIAIAAIAIAEIgHAPIgFgCIgHgBQgJABgEAHQgEAHAAATIAAAkgAk5C3IAAhUIATAAIAAAOQADgIAFgEQAFgEAIAAIAIAAIAHAEIgHAPIgFgCIgGgBQgKABgEAHQgEAHAAATIAAAkgAFBg8QgMgMAAgUQAAgUAMgNQAMgMAUAAQAUAAALALQALAMAAAVIAAADIhCAAQAAAMAHAGQAGAHAKAAQAJAAAGgEQAHgEAEgJIAQAJQgHANgKAGQgKAHgOAAQgUAAgMgNgAFSh1QgGAFgCAKIAtAAQgBgJgFgGQgGgEgKAAQgKAAgFAEgABmg0QgJgEgEgKIAQgIQABAFAFAEQAFADAHAAQAHAAAEgDQADgDAAgFQAAgHgNgEIgHgDQgNgFgFgHQgGgFAAgIQAAgMAJgGQAJgIAOABQAKAAAHADQAHAEADAGIgOAJQgBgEgEgBQgEgDgFAAQgFAAgDADQgEACAAAFQAAAGAPAGIAHACQAMAFAFAFQAFAGAAAJQAAANgJAGQgJAIgQAAQgMgBgIgEgAAZg0QgIgEgFgKIAQgIQACAFAFAEQAEADAIAAQAGAAAEgDQAEgDAAgFQAAgHgNgEIgHgDQgOgFgFgHQgFgFAAgIQAAgMAJgGQAIgIAPABQAJAAAHADQAHAEADAGIgNAJQgCgEgDgBQgEgDgFAAQgFAAgEADQgDACAAAFQAAAGAPAGIAHACQALAFAFAFQAFAGAAAJQAAANgJAGQgJAIgQAAQgMgBgIgEgAhNg7QgKgNAAgUQAAgVAKgMQALgMAQAAQAKAAAIAEQAHAEADAJIAAgPIATAAIAABUIgTAAIAAgLQgFAHgHAEQgGADgJABQgSgBgKgLgAg9hxQgGAIAAANQAAANAGAHQAGAIALgBQAKABAGgJQAHgHAAgNQAAgNgGgHQgGgHgLAAQgLAAgGAHgAGfgzIAAhUIATAAIAAAOQADgIAFgFQAFgDAIAAIAIABIAHACIgHAQIgFgCIgGAAQgKAAgEAHQgEAIAAARIAAAlgAEWgzIglgrIAAArIgTAAIAAiIIATAAIAABXIAjgjIAXAAIglAlIApAvgACwgzIAAhUIATAAIAABUgAh/gzIAAiIIATAAIAACIgAimgzIgzhCIAABCIgVAAIAAiBIAVAAIAAA1IAug1IAaAAIgzA6IA5BHgAlpgzIAAhUIAUAAIAAAOQADgIAFgFQAFgDAHAAIAIABIAIACIgHAQIgFgCIgHAAQgJAAgEAHQgEAIAAARIAAAlgAmVgzIAAgrQAAgQgEgGQgEgFgLAAQgGAAgFACQgGADgDAFIgDAHIAAAPIAAAmIgUAAIAAiIIASAAIAABDQAGgJAIgFQAIgDALAAQAJAAAHADQAGADAEAFIADAIIABARIAAAygAoEgzIAAiBIAVAAIAACBgACxiiQgEgEAAgFQAAgEAEgEQADgDAFAAQAFAAAEADQADAEAAAEQAAAGgDADQgEADgFABQgFAAgDgEg");
	this.shape.setTransform(55.3,24.6);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(2.7,5.8,105.2,37.7);


(lib.ClipGroup_2 = function() {
	this.initialize();

	// Ebene 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AqSOEIAA8HIUkAAIAAcHg");
	mask.setTransform(65.9,90);

	// Ebene 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1F775F").s().p("AghGBQgGgZgGgsIg3nDQgdivgFhEIgSjYIAtgFIAjBPQALAtAIAdQAGATANB+QAMB5AAAcQAAAgBJEAIBmFwIhmBgQhJivgLgog");
	this.shape.setTransform(15.3,60.1);

	this.shape.mask = mask;

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,30.6,120.2);


(lib.ClipGroup_1 = function() {
	this.initialize();

	// Ebene 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AqSOEIAA8HIUkAAIAAcHg");
	mask.setTransform(65.9,90);

	// Ebene 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D0D1D1").s().p("AHtB2IgRiXQgagfgLAAQgHAAgQgHIgOgHIuPgRIAAgaIOSAXIAaAJQAbALADAGIAlAtQAEAAAEBJIAEBMg");
	this.shape.setTransform(59.2,102.6);

	this.shape.mask = mask;

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(8.2,90.4,102.1,24.4);


(lib.ClipGroup = function() {
	this.initialize();

	// Ebene 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AqSOEIAA8HIUkAAIAAcHg");
	mask.setTransform(65.9,90);

	// Ebene 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D0D1D1").s().p("AGfBZIgDgOIjHghQjIghgJABQgMAAmbBBIAAAOIg2AAIAAgrIGghYIAGguIBZAAIgCAPQABARAHAKQAHALDUAqQBqAWBpAUIgFAXIgOAAIAAARg");
	this.shape.setTransform(68.4,171.1);

	this.shape.mask = mask;

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(21,162.1,95,17.9);


(lib.ClipGroup_1_1 = function() {
	this.initialize();

	// Ebene 2 (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("AraPcIAA+3IW1AAIAAe3g");
	mask_1.setTransform(73.2,98.9);

}).prototype = p = new cjs.Container();
p.nominalBounds = null;


(lib.ClipGroup_3 = function() {
	this.initialize();

	// Ebene 2 (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("AraPcIAA+3IW1AAIAAe3g");
	mask_1.setTransform(73.2,98.9);

	// Ebene 3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#2B2B2A").ss(0.2,0,0,4).p("ABqkjIjwGBIAjC6IAzALIAGhEIgph4IDXmHg");
	this.shape_1.setTransform(13.6,72.9);

	this.shape_1.mask = mask_1;

	this.addChild(this.shape_1);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,42.7,27.9,60.4);


(lib.entspa = function() {
	this.initialize();

	// Ebene 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACCB8IAAgLIAKAAQAHAAAEgCQAEgDAAgEIAAiPQAAgLgGgEQgFgEgOAAIAAgKIAsgCQAEAQAAAOQAKgPAKgHQAGgEAGgCQAGgCAHAAQAMAAAKAFQAKAFAIAKQAIAKAEANQAFANAAAOQAAAPgFAOQgEANgJAKQgIAJgKAGQgLAFgMAAQgNAAgLgHQgKgGgIgOIAAA4QAAAHAEADQADACAHAAIAKAAIAAALgADKg1QgHAEgFAIQgGAIgCALQgDALAAALQAAAOACAMQADAKAFAIQAFAHAHAEQAHAEAJAAQAIAAAHgEQAGgEAFgHQAEgIACgLQACgLAAgOQAAgNgCgLQgCgLgFgHQgEgHgGgEQgHgEgIAAQgIAAgHAEgAGcBCQgGgGgFgNQgNAOgJAFQgGADgHABQgHACgIAAQgKAAgIgCQgIgDgGgEQgFgEgDgGQgDgGAAgIQAAgKAGgJQAHgIAMgIQALgFARgFQASgFAVgCIAAgVQAAgGgCgFQgDgEgEgEQgJgIgNAAQgMAAgJAFQgIAEAAAEQAAACAEAGQAEAGAAAEQAAAGgFAEQgEAEgHAAQgHAAgFgEQgFgFAAgIQAAgIAEgGQAFgHAHgGQAJgFAKgDQAMgEANAAQALAAAJADQAKADAGAFQAHAFADAGQADAHAAAIIAABJQAAAJADAFQAEAFAFAAQAGAAAGgEIAGAIQgGAFgFADQgGADgHAAQgLAAgHgGgAFzAAQgMAEgIAFQgIAFgEAGQgEAHAAAKQAAALAGAGQAHAHAJAAQAJAAAHgEQAIgDAGgGQAGgGADgJQAEgIAAgLIAAgRIgdADgAAmBFQgJgEgJgGIgLAMIgHAAIgCg3IAIAAIAJAUQAFAJAGAFQAGAGAHADQAIACAJAAQAIAAAGgBQAGgCAFgEQAIgHAAgKQAAgJgFgFQgFgFgLgCIgmgJQgHgBgGgEQgGgCgEgEQgIgKAAgNQAAgIADgIQAEgIAFgGQAHgGAIgDQAJgEALAAQAJAAAIADQAIACAIAGIAKgKIAGAAIADAxIgJAAQgEgKgEgHQgEgIgFgFQgGgFgHgCQgGgDgJAAQgOAAgIAIQgIAGAAAKQAAAHAEAEQADAFAIADQAKADAjAGQAHACAGADQAGADAFADQAEAFACAHQADAGAAAHQAAAJgEAJQgEAIgHAGQgHAFgJAEQgJADgLAAQgLAAgJgDgAmdBDQgMgFgJgKQgJgJgFgNQgFgOAAgPQAAgOAFgOQAFgOAJgKQAIgKAMgFQAMgGANAAQAOAAAMAGQALAFAIAJQAIAKAEANQAFAOAAAQIhiAAQACAaAEAJQAGALAKAGQAKAGALAAQAIAAAGgCQAGgCAGgFIALgKQAFgGAEgIIAKAEQgFALgHAHQgGAIgIAFQgIAGgJACQgJADgKAAQgNAAgMgFgAmTg7QgGAEgFAHQgFAHgDAJQgDALAAAMIA7AAQAGAAADgDQACgEAAgHQAAgIgCgIQgDgHgFgFQgEgFgGgDQgHgDgGAAQgIAAgHADgAhQBDQgGgCgFgEQgFgFgCgGQgDgGAAgIIAAhaIgYAAIAAgKQAJgCAHgEQAIgFAEgHQAFgIADgKQACgKABgNIAKAAIAAA3IAsAAIAAAOIgsAAIAABWQAAALAFAHQAFAGAJAAQAGAAAEgDQAFgCADgFQADgFACgIIACgRIAKAAQgBANgDAKQgDAKgFAHQgGAHgHADQgIAEgKAAQgIAAgHgDgAjTBEIAAgLIAHAAQAJAAAEgDQAEgDAAgHIAAg4QAAgLgCgHQgCgIgEgFQgDgGgGgCQgGgDgIAAQgIAAgHADQgGAEgGAGQgFAGgDAJQgDAJAAALIAAAxQAAAIADADQAEADAIAAIAJAAIAAALIhIAAIAAgLIAJAAQAHAAAEgDQAEgDAAgEIAAhXQAAgJgFgEQgFgFgJAAIgHAAIAAgKIAugCQADAOABAQQAEgHAGgGQAFgGAHgEQAGgDAHgCQAHgCAIAAQAKAAAIADQAIAEAGAGQAFAGADAJQADAJAAALIAABBQAAAIAEADQADADAIAAIAJAAIAAALg");
	this.shape.setTransform(48.7,17.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(3.3,4.7,90.9,25);


(lib.endcopy_mc = function() {
	this.initialize();

	// Ebene 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AmEDMIAAh6IATAAIAAAOQADgJAHgEQAIgEAKAAQAQAAALAMQAKAMAAAVQAAAUgKAMQgKANgSAAQgJAAgHgEQgGgDgFgIIAAAygAlsBnQgGAHAAANQAAANAHAIQAGAHALABQAKAAAGgIQAHgHgBgNQAAgOgGgHQgGgIgLABQgKgBgHAIgAHrCcQgKgMAAgUQAAgVAKgMQALgMAQAAQAKAAAIAEQAGAEAEAJIAAhDIATAAIAACIIgTAAIAAgLQgFAIgHADQgGAEgJAAQgSAAgKgNgAH7BnQgHAHABAOQgBANAHAHQAGAIAKAAQAKgBAHgHQAGgIABgNQAAgNgHgHQgFgIgMABQgKgBgGAIgAE/CcQgKgMAAgUQAAgVALgMQAKgMARAAQAKAAAHAEQAHAEAEAJIAAgOIASAAIAABTIgSAAIAAgLQgFAIgHADQgHAEgJAAQgRAAgLgNgAFPBnQgGAHAAAOQAAANAGAHQAGAIALAAQAKgBAGgHQAHgIAAgNQAAgNgGgHQgGgIgLABQgLgBgGAIgADfCjQgMgEgJgJQgKgKgFgNQgFgMAAgOQAAgOAFgNQAFgMAKgJQAKgKAMgFQAMgFAOABQAMAAAKADQALADAJAGIgBAVQgJgHgJgEQgKgDgMAAQgUAAgOANQgNANAAAWQAAAVANAOQANANATAAQAMAAAKgEQAKgEAKgIIAAAXQgJAHgJACQgKAEgMAAQgPgBgNgFgAglCkQgJgFgEgJIAQgIQACAFAEAEQAFADAHAAQAHAAAEgDQADgDABgFQgBgGgNgFIgGgDQgOgGgFgGQgFgFgBgJQAAgKAKgIQAIgGAPAAQAJgBAFAEQAHAEADAGIgMAJQgBgDgEgCQgDgDgGAAQgFAAgDADQgDACgBAEQABAHAPAGIAHACQAJAFAFAFQAFAGAAAJQAAAMgJAIQgHAGgQABQgMAAgIgFgAhyCkQgIgFgEgJIAQgIQABAFAFAEQAEADAIAAQAHAAAEgDQADgDAAgFQAAgGgNgFIgHgDQgOgGgFgGQgFgFAAgJQAAgKAJgIQAIgGAPAAQAJgBAIAEQAGAEADAGIgNAJQgBgDgEgCQgEgDgFAAQgFAAgDADQgEACAAAEQAAAHAPAGIAHACQALAFAGAFQAEAGAAAJQAAAMgJAIQgIAGgQABQgMAAgJgFgAjTCcQgMgMAAgUQAAgUANgNQALgMAUAAQAUAAALAMQAMALAAAVIAAADIhDAAQAAAMAHAGQAGAHAKAAQAJAAAHgEQAGgEAEgIIARAJQgIAMgKAGQgKAGgOABQgUAAgMgNgAjCBjQgFAFgDAKIAuAAQgBgKgGgFQgGgEgKAAQgKAAgFAEgAGkClIAAhTIATAAIAAANQAEgJAEgEQAFgDAIAAIAIABIAHACIgHARIgEgDIgHAAQgKgBgDAIQgFAHAAASIAAAlgAkbClIAAhTIATAAIAAANQADgJAFgEQAFgDAHAAIAJABIAHACIgHARIgFgDIgGAAQgKgBgEAIQgEAHAAASIAAAlgAmlClIgPgWIAAgBIgGgKIgDAGIgEAFIgPAWIgVAAIAggtIgbgmIAUAAIAMARIAEAFIACAFIACgEIAEgGIAMgRIAUAAIgbAmIAgAtgAo0ClIAAiAIBHAAIAAARIgyAAIAAAhIAyAAIAAASIgyAAIAAApIAyAAIAAATgAA1BmQgHgDgGgHQgHgGgCgHQgEgIAAgIQAAgJAEgIQADgHAGgGQAGgHAHgCQAIgEAIAAQAKAAAHAEQAIADAGAGQAGAGADAHQADAIAAAJQAAAJgDAHQgDAIgHAFQgFAHgIADQgIADgJAAQgIAAgIgDgAA4AdQgGADgGAFQgEAFgEAHQgCAGAAAIQAAAHACAGQADAHAFAFQAGAFAGADQAGACAHABQAIgBAGgCQAHgCAFgGQAFgFADgGQACgGABgIQgBgHgCgHQgDgHgEgFQgGgFgGgDQgHgCgHAAQgIAAgGACgABPBVIgJgTIgIAAIAAATIgKAAIAAgvIASAAQAKAAAGAEQAFADAAAGQAAAGgDADQgDADgFABIALAVgAA+A8IAHAAQAGAAADgCQACgCAAgDQAAgFgCgCQgDgBgGAAIgHAAgAFWhOQgKgMAAgVQAAgTAKgNQALgMAQAAQAKAAAIAEQAHAFADAHIAAgNIAUAAIAABTIgUAAIAAgLQgEAHgIAEQgGADgJAAQgRAAgLgMgAFmiDQgGAHAAAOQAAANAGAIQAGAGALABQAKgBAHgHQAGgIAAgNQAAgNgGgHQgGgIgLAAQgKAAgHAIgAEHhOQgNgMAAgVQABgTANgNQAMgMAVAAIAMABIAKAEIAAAVQgEgFgGgCQgGgDgHAAQgLAAgIAIQgGAHgBANQABANAGAIQAIAHAMAAQAHAAAGgDQAFgCAEgGIAAAXQgFADgHABQgGABgGAAQgUAAgMgMgAAxhOQgMgMAAgVQAAgTANgMQALgNAUAAQAUAAALAMQALALAAAUIAAAEIhCAAQAAAMAHAHQAGAGAKAAQAJAAAHgEQAGgEAEgIIARAJQgIAMgKAHQgKAFgOAAQgUAAgMgMgABCiGQgGAEgCAJIAuAAQgBgIgGgFQgGgFgKAAQgJAAgGAFgAl8hOQgMgMAAgVQAAgTANgMQALgNAUAAQAUAAALAMQALALAAAUIAAAEIhCAAQABAMAGAHQAGAGAKAAQAKAAAFgEQAHgEAEgIIAQAJQgHAMgKAHQgKAFgOAAQgUAAgMgMgAlriGQgFAEgDAJIAuAAQgCgIgFgFQgGgFgKAAQgJAAgGAFgAH4hFIAAgrQAAgQgDgFQgEgGgLAAQgHAAgFADQgFACgDAEIgDAIIAAAPIAAAmIgUAAIAAhTIASAAIAAANQAGgIAHgEQAJgEAKAAQAJAAAIADQAGADADAGIADAIIABAPIAAAzgADThFIAAhTIATAAIAABTgACPhFIAAhTIATAAIAAANQAEgJAEgDQAGgEAHAAIAIABIAHADIgGAQIgFgDIgHgBQgKAAgDAIQgFAHAAATIAAAkgAAAhFIAAgrQAAgQgDgGQgDgFgKAAQgLAAgEAHQgGAHABASIAAAmIgUAAIAAgrQAAgPgEgGQgDgGgKAAQgFAAgEADQgFACgDAEQgCAEAAADIgBAQIAAAmIgTAAIAAhTIASAAIAAANQAFgIAIgEQAHgEAKgBQAKABAGAEQAHAEADAIQAGgJAHgDQAIgEAJgBQAIABAFADQAGACAEAHIACAGIAAALIAAA5gAiQhFIgQghIgyAAIgQAhIgVAAIA+iGIA+CGgAi7icIgCAHIgNAdIAkAAIgOgdIgCgHIgCgHIgDAHgAmwhFIAAhTIATAAIAABTgAo0hFIAAiAIAcAAQAbgBAMADQALADAIAGQALAJAHAOQAFANAAARQAAARgFANQgHAOgLAIQgIAHgLADQgKACgYAAgAofhYIASAAQAOAAAHgCQAHgCAFgFQAIgGAEgJQADgJAAgMQAAgMgDgKQgEgKgIgFQgFgFgIgCQgHgCgQAAIgPAAgADUi0QgEgEAAgEQAAgFAEgDQADgEAFAAQAFAAAEADQADAEAAAFQAAAEgDAFQgEACgFAAQgFAAgDgDgAmvi0QgEgEABgEQgBgFAEgDQAEgEAEAAQAFAAAEADQADAEAAAFQAAAEgDAFQgEACgFAAQgEAAgEgDg");
	this.shape.setTransform(60.1,13.4);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(3.5,-7,113.1,40.9);


(lib.copy_02_mc = function() {
	this.initialize();

	// Ebene 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIugVIAbAAIAXAzIADAIIACAMIADgKIAEgKIAXgzIAaAAIg4BvgALxBIQgQgQABgaQAAgZAPgOQAQgQAYAAQAaAAAPAPQAOANAAAaIAAAFIhVAAQAAAPAJAIQAHAIAOAAQALAAAIgFQAJgFAFgLIAVAMQgJAQgNAIQgOAIgSAAQgZAAgPgQgAMHAAQgIAFgCAMIA5AAQgBgLgHgGQgIgEgMAAQgMAAgHAEgAGDBIQgPgQgBgaQAAgZAQgOQAQgQAYAAQAaAAAPAPQAOANAAAaIAAAFIhVAAQAAAPAIAIQAJAIANAAQAMAAAIgFQAHgFAGgLIAVAMQgJAQgNAIQgNAIgTAAQgZAAgPgQgAGYAAQgHAFgDAMIA7AAQgCgLgHgGQgHgEgNAAQgMAAgIAEgADLBOQgOgKgDgSIAVgKQADALAIAGQAIAGAMAAQAMAAAIgHQAGgGAAgLQAAgPgXgLIgGgDQgbgLgJgLQgJgKAAgQQAAgUAOgMQAOgNAWAAQASAAAMAHQAMAHAFANIgVALQgFgIgGgDQgGgEgHAAQgLAAgGAGQgHAFAAAKQAAAPAcAMIAEACQAXAKAKAKQAJALAAAQQAAAXgPAOQgPAOgZAAQgUAAgOgKgAiCBIQgPgQAAgaQAAgZAPgOQARgQAYAAQAaAAAOAPQAPANAAAaIAAAFIhWAAQABAPAIAIQAIAIAOAAQALAAAIgFQAIgFAFgLIAWAMQgKAQgNAIQgNAIgSAAQgaAAgPgQgAhsAAQgHAFgDAMIA6AAQgCgLgHgGQgHgEgMAAQgMAAgIAEgAk+BIQgPgQAAgaQAAgZAPgOQARgQAYAAQAZAAAPAPQAOANAAAaIAAAFIhUAAQAAAPAIAIQAIAIAOAAQALAAAIgFQAIgFAGgLIAVAMQgKAQgNAIQgNAIgSAAQgZAAgQgQgAkoAAQgIAFgCAMIA6AAQgBgLgIgGQgHgEgNAAQgLAAgIAEgAmjBSQgKgGgHgMIAVgLQACAIAGAEQAGAEAJAAQAJAAAFgDQAEgEAAgHQABgIgSgHIgIgDQgRgHgHgHQgGgIgBgKQAAgMALgJQAMgJASAAQAMAAAKAEQAIAFAEAIIgRAKQgCgDgFgDQgFgDgGAAQgHAAgEAEQgFADABADQgBAJAUAHIAJADQAOAGAHAHQAGAIAAALQAAAQgLAJQgMAJgVAAQgPAAgKgGgAptBIQgNgPgBgbQABgaANgNQANgQAWAAQAMAAAJAGQAKAFAEAKIAAhVIAYAAIAACsIgYAAIAAgOQgGAKgJAEQgJAFgLAAQgXAAgMgQgApZAEQgIAKAAARQAAARAIAJQAHAJAOAAQANAAAJgKQAIgKAAgQQAAgRgIgJQgHgHgPAAQgNAAgIAHgAt1BKQgNgOAAgfIAAgyIAZAAIAAA6QAAAPAGAHQAHAHAOAAQAOAAAHgHQAGgHABgPIAAg6IAXAAIAAAyQAAAfgMAOQgMAOgaAAQgcAAgMgOgANqBTIAAisIAZAAIAACsgAKuBTIAAhoIAZAAIAABogAFABTIAAhoIAYAAIAABogABCBTIAAg2QAAgVgEgHQgGgFgMAAQgKAAgGADQgHABgDAGQgDAEgBAGQgCAGAAANIAAAwIgVAAIAAhoIAUAAIAAARQAIgLAJgFQALgFAOAAQAMAAAIAEQAIAEAFAHQACAEACAGIABATIAABAgAjEBTIAAhoIAYAAIAABogAqrBTIAAg2QAAgVgGgHQgEgFgOAAQgIAAgHADQgGABgFAGQgCAEgBAGQgCAGABANIAAAwIgZAAIAAhoIAYAAIAAARQAGgLALgFQAJgFAOAAQAMAAAJAEQAIAEAFAHQADAEABAGIABATIAABAgAKvg4QgEgFAAgGQAAgGAEgFQAFgEAGAAQAGAAAFAEQAFAEgBAHQABAGgFAFQgFAEgGAAQgGAAgFgEgAFCg4QgGgFAAgGQAAgGAGgFQAEgEAGAAQAGAAAFAEQAFAEAAAHQAAAGgFAFQgFAEgGAAQgGAAgEgEgAjDg4QgFgFAAgGQAAgGAFgFQAFgEAFAAQAHAAAEAEQAFAEAAAHQAAAGgFAFQgEAEgHAAQgFAAgFgEg");
	this.shape.setTransform(93.5,5.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(3.6,-3.2,179.8,18.1);


(lib.copy_01_mc = function() {
	this.initialize();

	// Ebene 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AOaBJQgPgQAAgaQAAgZAQgOQAQgQAYAAQAaAAAOAPQAPANAAAaIAAAFIhVAAQAAAPAIAIQAIAIAOAAQALAAAIgFQAIgFAGgLIAVAMQgJAQgOAIQgNAIgSAAQgZAAgQgQgAOwABQgHAFgDAMIA6AAQgBgLgHgGQgIgEgMAAQgMAAgIAEgAKsBJQgQgQAAgaQAAgZAQgOQAQgQAbAAQAIAAAHACQAHABAGAEIAAAZQgGgGgHgCQgHgDgJAAQgPAAgJAIQgJAKAAAQQAAAQAJAKQAJAJAQAAQAJAAAHgDQAHgDAFgHIAAAcQgHAEgHACQgIACgJAAQgZAAgPgQgAIJBTQgKgGgGgMIAUgLQACAIAGAEQAGAEAKAAQAIAAAFgDQAFgEAAgHQAAgIgRgHIgJgDQgRgHgHgHQgGgIAAgKQAAgMALgJQALgJASAAQANAAAJAEQAIAFAEAIIgRAKQgCgDgFgDQgEgDgHAAQgHAAgEAEQgEACAAAEQAAAJATAHIAJADQAPAGAGAHQAGAIAAALQAAAQgLAJQgMAJgUAAQgQAAgKgGgADYBJQgQgQAAgaQAAgZARgOQAQgQAaAAQAJAAAHACQAHABAGAEIAAAZQgGgGgHgCQgIgDgJAAQgPAAgJAIQgIAKAAAQQAAAQAJAKQAJAJAQAAQAIAAAHgDQAHgDAGgHIAAAcQgHAEgIACQgIACgIAAQgZAAgQgQgAA2BTQgLgGgGgMIAVgLQACAIAGAEQAGAEAJAAQAJAAAEgDQAFgEAAgHQAAgIgRgHIgIgDQgRgHgHgHQgHgIAAgKQAAgMALgJQALgJATAAQAMAAAJAEQAJAFAEAIIgRAKQgCgDgFgDQgFgDgGAAQgHAAgEAEQgFACAAAEQAAAJATAHIAKADQAOAGAHAHQAGAIAAALQAAAQgMAJQgLAJgVAAQgPAAgKgGgAiKBJQgPgQAAgaQAAgZAPgOQAQgQAZAAQAZAAAPAPQAOANAAAaIAAAFIhVAAQABAPAIAIQAIAIANAAQAMAAAIgFQAIgFAFgLIAVAMQgJAQgNAIQgNAIgSAAQgaAAgPgQgAh0ABQgIAFgCAMIA6AAQgCgLgHgGQgHgEgNAAQgMAAgHAEgAlCBPQgNgKgEgSIAVgKQADALAIAGQAIAGANAAQAMAAAHgHQAHgGAAgLQAAgPgYgLIgFgDQgcgLgJgLQgJgKAAgQQAAgUAOgMQAOgNAWAAQASAAAMAHQAMAHAFANIgVALQgFgIgGgDQgGgEgHAAQgLAAgGAGQgHAFAAAKQAAAPAcAMIAEACQAYAJAJALQAJALAAAQQAAAXgPAOQgOAOgZAAQgVAAgOgKgAqRBJQgPgQAAgaQAAgZAQgOQAQgQAYAAQAaAAAOAPQAPANAAAaIAAAFIhVAAQAAAPAIAIQAIAIAOAAQALAAAIgFQAIgFAGgLIAVAMQgJAQgOAIQgNAIgSAAQgZAAgQgQgAp7ABQgHAFgDAMIA6AAQgBgLgHgGQgIgEgMAAQgMAAgIAEgAvXBLQgMgOAAgfIAAgyIAYAAIAAA6QAAAPAHAHQAGAHAOAAQAPAAAGgHQAHgHAAgPIAAg6IAYAAIAAAyQAAAfgMAOQgNAOgaAAQgcAAgMgOgAQTBUIAAhoIAYAAIAAARQAEgLAGgFQAHgFAJAAIALABIAJAEIgIATIgHgCIgIgBQgMAAgGAIQgFAKAAAXIAAAugANaBUIAAg2QAAgVgFgHQgFgFgNAAQgJAAgGADQgHABgEAGQgCAEgBAGQgCAGAAANIAAAwIgYAAIAAisIAXAAIAABVQAHgLAKgFQAKgFAOAAQAMAAAJAEQAIAEAFAHQACAEACAFIABAUIAABAgAJoBUIAAhoIAZAAIAABogAGHBUIAAg2QAAgVgFgHQgFgFgNAAQgJAAgHADQgGABgEAGQgDAEgBAGQgBAGAAANIAAAwIgYAAIAAisIAXAAIAABVQAHgLAKgFQAKgFAOAAQAMAAAIAEQAIAEAFAHQADAEABAFIABAUIAABAgACVBUIAAhoIAYAAIAABogAjNBUIAAhoIAZAAIAABogAnKBUIAAg2QAAgVgFgHQgFgFgNAAQgJAAgHADQgGABgEAGQgDAEgBAGQgBAGAAANIAAAwIgYAAIAAhoIAXAAIAAARQAHgLAKgFQAKgFAOAAQAMAAAIAEQAIAEAFAHQADAEABAFIABAUIAABAgArTBUIAAisIAYAAIAACsgAsNBUIAAg2QAAgVgFgHQgFgFgNAAQgJAAgHADQgGABgEAGQgDAEgBAGQgBAGAAANIAAAwIgYAAIAAisIAXAAIAABVQAHgLAKgFQAKgFAOAAQAMAAAIAEQAIAEAFAHQADAEABAFIABAUIAABAgAxYBUIAAiiIBbAAIAAAXIhBAAIAAApIBBAAIAAAVIhBAAIAABNgAulgtQgEgEAAgGQAAgFAEgEQAEgEAGAAQAFAAAEAEQAEAEAAAFQAAAGgEAEQgDAEgGAAQgGAAgEgEgAvOgtQgEgEAAgGQAAgFAEgEQAEgEAGAAQAFAAAEAEQAEAEAAAFQAAAGgDAEQgEAEgGAAQgGAAgEgEgAJqg3QgFgFAAgGQAAgGAFgFQAEgEAGAAQAHAAAEAEQAFAEAAAHQAAAGgFAFQgEAEgHAAQgGAAgEgEgACWg3QgFgFAAgGQAAgGAFgFQAFgEAGAAQAGAAAFAEQAEAEAAAHQAAAGgEAFQgFAEgGAAQgGAAgFgEgAjLg3QgFgFAAgGQAAgGAFgFQAEgEAGAAQAHAAAEAEQAFAEAAAHQAAAGgFAFQgEAEgHAAQgGAAgEgEg");
	this.shape.setTransform(115.3,5.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(3.9,-3.2,222.8,17.9);


(lib.card = function() {
	this.initialize();

	// Ebene 4
	this.instance = new lib.GreenCard();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,102,66);


(lib.C4_3 = function() {
	this.initialize();

	// Ebene 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJ4BhQgIgDgGgGQgFgFgDgIQgDgIAAgKIAUAAQAAAKADAFQADAEAFADQAFADAHAAQAFAAAFgCQAEgCADgDQACgDACgGQABgFAAgHIAAgMQgGAGgHADQgGAEgJAAQgJAAgHgEQgIgDgFgHQgGgGgDgIQgDgJAAgKQAAgIADgIQADgJAGgHQAFgGAIgDQAIgEAIAAQAJAAAHADQAHADAFAGIAAgKIAUAAIAABVQAAANgBAHQgCAHgEAGQgDAEgEADIgIAGQgJAEgLAAQgKAAgIgDgAJ+gRQgEACgDAEQgEAEgBAFQgCAEAAAGQAAAGACAGQABAFAEADQADAEAEACQAFACAFAAQAGAAAEgCQAFgCADgEQAEgEABgFQACgFAAgHQAAgGgCgDQgCgFgDgEQgDgEgFgCQgEgCgGAAQgFAAgFACgAFcBkIAAiHIAUAAIAAAKQAGgGAHgDQAGgDAIAAQAJAAAIAEQAIADAFAGQAGAHADAJQADAIAAAIQAAAKgDAJQgDAIgGAGQgFAHgIADQgIAEgJAAQgIAAgGgEQgHgDgGgGIAAA6gAF+gRQgFACgDAEQgEAEgCAFQgBADAAAHQAAAGABAFQACAFAEAEQADAEAFACQAEACAGAAQAFAAAFgCQAEgCADgEQAEgEACgFQABgFAAgGQAAgGgBgEIgFgJQgEgEgEgCQgFgCgFAAQgGAAgEACgADsBkIAAiHIAUAAIAAAKQAHgGAGgDQAHgDAIAAQAJAAAIAEQAHADAGAGQAGAHADAJQADAIAAAIQAAAKgDAJQgEAIgFAGQgGAHgIADQgHAEgJAAQgIAAgHgEQgGgDgHgGIAAA6gAEOgRQgEACgEAEQgDAEgCAFQgCADAAAHQAAAGACAFQACAFADAEQADAEAFACQAFACAFAAQAGAAAEgCQAFgCADgEQADgEACgFQACgFAAgGQAAgGgCgEIgFgJQgDgEgFgCQgEgCgGAAQgFAAgFACgACVAzQgIgEgHgGQgGgGgEgJQgEgIAAgKQAAgIAEgJQAEgIAGgGQAGgHAJgDQAJgEAKAAQAJAAAJAEQAJADAGAHQAHAGADAIQAEAJAAAIQAAAKgEAIQgDAJgHAGQgGAGgJAEQgJAEgJAAQgKAAgJgEgACdgRQgFACgEAEQgDAEgCAFQgCAEAAAGQAAAGACAFQACAGADADQAEAEAFACQAFACAFAAQAGAAAFgCQAFgCAEgEQADgDACgGQACgFAAgGQAAgGgCgEQgCgFgDgEQgEgEgFgCQgFgCgGAAQgFAAgFACgAg6A0QgIgDgGgFQgFgGgEgHQgEgIgBgKIAVgFQABALADAFQADAFAFADQAGADAGAAQAFAAAEgCQAEgCAEgDQADgDABgEQACgFAAgFQAAgGgCgEQgDgDgFgDIgTgKIgEgBQgIgDgFgEQgFgEgEgEQgEgFgBgFQgCgFAAgGQAAgIADgHQADgGAGgFQAGgFAHgDQAIgDAJAAQAGAAAGABQAFACAFADQAEACAEAFIAIAKIgRALQgFgIgFgDQgEgDgHAAQgJAAgGAFQgGAFAAAHQAAAIAHAEQAEADATAHQAIAEAGAEQAGAEAEAFQAEAFABAGQABAEAAAHQAAAKgBAIQgDAIgGAHQgGAGgIADQgJAEgJAAQgJAAgIgDgAjNAzQgIgDgGgGQgFgGgDgJQgEgJAAgKQAAgIADgJQADgJAGgGQAGgGAIgEQAIgDAJAAQAKAAAIADQAHADAGAHQAFAGADAIQADAJAAAIIAAAFIg/AAIACAKQACAFADADIAHAFQAEABAFAAQAHAAAFgDQAGgEAGgKIARAKIgJALQgEAFgFADQgFADgGACQgGACgHAAQgKAAgIgEgAingCQgCgIgFgEQgGgFgIAAQgHAAgFAFQgGAEgCAIIApAAIAAAAgAp5A1QgHgBgHgDQgGgDgGgEIgLgIIgJgLIgHgMIgEgMQgBgHAAgIIABgPIAEgNIAHgNIAJgLIALgJQAGgEAGgCIAOgFQAIgBAHAAIAPABQAHACAGADQAHACAGAEIALAJIAJALQAEAGACAHQADAGABAHQACAHAAAIQAAAHgCAHQgBAFgDAHIgGAMIgJALIgLAJQgGAEgHADQgGADgHABQgIACgHAAQgHAAgIgCgAp/hBQgJAEgHAHQgHAHgEAKQgEAKAAALQAAALAEAIQAEAJAHAHQAHAIAKADQAJAFALAAQAKAAAKgFQAJgEAIgHQAHgHAEgKQAEgHAAgLQAAgLgEgKQgEgKgHgHQgHgHgKgEQgJgEgLAAQgLAAgKAEgAIxA0IAAgyQAAgLgEgFQgDgFgKAAQgFAAgEACQgDACgCADQgDAEgBAFIgBA3IgUAAIAAhXIAUAAIAAAJQAGgGAGgDQAFgCAHAAQAIAAAGACQAGADAEAEQAEAFACAGQACAHAAAKIAAA0gAHLA0IAAhXIAVAAIAABXgABOA0IAAg0QAAgJgEgFQgDgFgIAAQgGAAgEACQgDABgDAEIgDAJIgBAMIAAArIgUAAIAAiXIAUAAIAABIQAGgFAFgDQAGgCAHAAQAIAAAHADQAHADAEAGQADAEABAGQACAFAAAKIAAA0gAkRA0IAAgyQAAgLgDgFQgEgFgJAAQgGAAgDACQgEACgCADQgCAEgBAFIgBA3IgUAAIAAhXIAUAAIAAAJQAGgGAFgDQAFgCAIAAQAIAAAGACQAGADAEAEQAEAFACAGQACAHAAAKIAAA0gAl2A0IAAhXIAUAAIAABXgAmkA0IAAiXIAUAAIAACXgAnTA0IAAgyQAAgLgDgFQgEgFgJAAQgGAAgDACQgEACgCADQgCAEgBAFIgBA3IgUAAIAAhXIAUAAIAAAJQAGgGAFgDQAFgCAIAAQAIAAAGACQAGADAEAEQAEAFACAGQACAHAAAKIAAA0gAiJAQIAAgQIApAAIAAAQgAHMg+QgEgEAAgFQAAgGAEgEQAEgEAGAAQAFAAAEAEQAEAEAAAGQAAAFgEAEQgEAEgGAAQgFAAgEgEgAl1g+QgEgEAAgFQAAgGADgEQAEgEAGAAQAGAAADAEQAEAEAAAGQAAAFgEAEQgEAEgFAAQgGAAgDgEg");
	this.shape.setTransform(72.3,10.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(3,0.7,138.6,20.2);


(lib.C4_2 = function() {
	this.initialize();

	// Ebene 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AraBiQgJgCgFgHQgGgFgDgIQgDgIAAgKIAUAAQABALADAEQADAEAFADQAFADAHAAQAFAAAFgCQAEgBADgEQACgDABgFQACgFAAgHIAAgNQgHAGgGADQgHAEgIAAQgJAAgIgEQgHgDgGgHQgFgFgDgJQgDgJAAgKQAAgJADgHQADgJAFgGQAGgHAHgDQAIgDAJgBQAIAAAIAEQAGACAGAHIAAgLIAUAAIAABVQAAANgCAHQgBAHgEAHQgDADgEAEIgIAFQgJAFgLAAQgLAAgHgEgArUgQQgEADgDADQgEAEgCAFQgCAEAAAGQAAAGACAGQACAFAEAEQADADAEACQAEACAGABQAGgBAEgCQAFgCADgDQADgFACgEQACgGAAgHQAAgGgCgDQgCgFgDgEQgDgDgFgDQgEgCgGAAQgGAAgEACgAH/A0QgHgDgGgGQgGgGgDgIQgDgKgBgKQAAgJAEgIQACgJAHgGQAFgGAIgDQAIgEAJAAQAKAAAIAEQAHADAGAGQAFAGADAIQADAJAAAIIAAAGIg/AAIACAKQACAEADADIAHAFQAEACAFAAQAHAAAGgEQAFgEAGgJIARAJIgIALQgFAFgFAEQgFADgGABQgGACgHAAQgJAAgJgEgAIlgBQgCgIgFgEQgFgEgJgBQgHABgFAEQgGAFgBAHIAoAAIAAAAgAGcA1QgHgDgGgGIAAAJIgVAAIAAiXIAVAAIAABLQAGgHAHgDQAGgCAIgBQAJAAAHAEQAJADAFAHQAGAFADAJQADAIAAAIQAAALgDAIQgDAJgGAGQgFAGgIAEQgIAEgJAAQgIAAgGgDgAGcgQQgEADgEADQgDAEgCAFQgCADAAAHQAAAGACAGQACAEADAFQADADAFACQAFACAFABQAGgBAEgCIAIgFIAGgJQABgGAAgGQAAgGgBgEQgCgFgEgEQgDgDgFgDQgEgCgGAAQgFAAgFACgABiA1QgGgDgGgGQgFgFgCgHQgCgGAAgKIAAgyIAUAAIAAAxQAAAMAFAFQADAGAJAAQAKAAADgGQAFgFAAgMIAAgxIAUAAIAAAyQAAAKgCAGQgCAHgFAFQgGAGgGADQgIADgJAAQgIAAgIgDgAg5A0QgIgDgGgGQgGgGgDgIQgDgKAAgKQAAgJADgIQADgJAGgGQAFgGAJgDQAHgEAKAAQAKAAAIAEQAHADAFAGQAGAGADAIQABAJAAAIIAAAGIg+AAIACAKQADAEACADIAIAFQADACAGAAQAHAAAFgEQAFgEAGgJIAPAJIgGALQgEAFgGAEQgEADgHABQgFACgHAAQgKAAgIgEgAgTgBQgDgIgFgEQgFgEgIgBQgHABgGAEQgFAFgCAHIApAAIAAAAgAi1A2QgHgBgHgDQgGgCgGgFQgFgDgFgGIgJgKIgHgMQgCgHgBgFIgCgOQAAgJACgGIADgPIAHgMIAJgKIALgJQAGgFAHgCIANgEQAIgCAIAAQAIAAAIACQAHABAHAEQAHADAHAGIAMANIgPAOQgEgGgFgEQgEgFgGgDIgLgDQgFgCgHAAQgLAAgKAEQgJAEgHAHQgHAIgEAJQgEALAAALQAAAKAEAIQAEAJAHAIQAHAHAJAEQAKAEAKAAQAIAAAHgDQAHgDAGgFQAGgEAEgHQADgHAAgHIgiAAIAAgSIA6AAIAAAHQAAAMgDAKQgDAJgHAKQgEAGgGAFQgGAFgHADQgGADgJACQgHACgHAAQgIAAgHgCgAnWA0QgIgDgHgGQgFgGgDgIQgDgKAAgKQAAgJACgIQADgJAGgGQAGgGAIgDQAIgEAKAAQAJAAAIAEQAIADAFAGQAGAGACAIQADAJAAAIIAAAGIg/AAIACAKQACAEADADIAHAFQAEACAFAAQAIAAAEgEQAGgEAGgJIARAJIgJALQgEAFgFAEQgFADgGABQgGACgHAAQgJAAgIgEgAmxgBQgCgIgFgEQgGgEgHgBQgIABgFAEQgGAFgCAHIApAAIAAAAgApuA1QgIgDgFgGQgFgFgCgHQgCgGAAgKIAAgyIAUAAIAAAxQAAAMAEAFQAFAGAJAAQAIAAAEgGQAFgFAAgMIAAgxIAUAAIAAAyQAAAKgCAGQgCAHgFAFQgFAGgIADQgHADgIAAQgKAAgGgDgALjA1IAAgxQAAgKgDgGQgCgFgIgBQgFABgDABQgDABgBAEQgDADgBAGIgBAJIAAAuIgUAAIAAgxQAAgKgEgFQgDgHgHAAQgEABgDABQgDABgCAEQgCADgBAGIgCAJIAAAuIgUAAIAAhXIAUAAIAAAJQAHgGAEgDQAEgCAHAAQAIAAAFAEQAHADADAHQAGgHAGgDQAHgEAIAAQAHAAAGACQAGADADAEQAEAFACAHQACAHAAAIIAAA1gAJQA1IAAhXIAVAAIAABXgAEYA1IAAiXIAUAAIAACXgADpA1IAAg1QAAgHgDgFQgEgGgIAAQgFABgFABQgDABgCAEIgEAJIgBANIAAAqIgUAAIAAiXIAUAAIAABIQAGgFAGgDQAFgCAHAAQAIAAAHAEQAHACAEAHQADAEABAFQACAGAAAIIAAA1gAAXA1IAAhDIgIAAIAAgUIAIAAIAAghQgBgKACgFQACgGADgDQADgEAHgDQAGgCAGgBQAHAAAIADIAAAWQgKgFgEAAQgFAAgCAEQgCADAAALIAAAdIAXAAIAAAUIgXAAIAABDgAlOA1IAAgxQAAgMgDgEQgEgGgKAAQgFABgEABQgDACgCADQgCAEgCAFIgBA3IgTAAIAAhXIATAAIAAAJQAGgGAGgDQAFgCAIAAQAHAAAGACQAHADADAEQAFAFABAGQACAIAAAIIAAA1gAoeA1IAAhDIgJAAIAAgUIAJAAIAAggIAUAAIAAAgIAQAAIAAAUIgQAAIAABDgAB8g0QgDgEAAgGQAAgEADgFQAEgDAFAAQAGAAAEADQAEAFAAAEQAAAGgEAEQgEADgGABQgFgBgEgDgABXg0QgEgEgBgGQABgEAEgFQAEgDAFAAQAFAAAEADQAEAFgBAEQAAAGgDAEQgEADgFABQgFgBgEgDgAJRg9QgDgEAAgFQgBgGAEgEQAEgDAGAAQAGAAADADQAEAEAAAGQAAAFgEAEQgEAEgGAAQgFAAgEgEg");
	this.shape.setTransform(79,10.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(2.9,0.5,152.1,20.4);


(lib.C4_1 = function() {
	this.initialize();

	// Ebene 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AlrgLIgPBTIgWAAIAdiVIAwBqIAyhqIAaCVIgVAAIgOhTIgpBZgADHBHQgIgEgGgFQgGgHgDgIQgDgJAAgKQAAgLADgIQADgJAGgFQAFgFAIgEQAIgDAKAAQAJAAAIADQAIADAFAGQAGAFADAIQACAJAAAKIAAAFIg/AAIACAKQACAEADADIAHAGQAEABAFAAQAIAAAFgDQAFgFAGgJIARAJIgIAMQgFAFgFADQgFADgGACQgGABgHAAQgJAAgIgDgADtAQQgDgIgFgFQgFgDgIAAQgIAAgFADQgGAFgBAIIApAAIAAAAgAgyBHQgIgEgGgFQgFgHgDgIQgEgJAAgKQAAgLADgIQADgJAGgFQAGgFAIgEQAIgDAJAAQAKAAAIADQAHADAGAGQADAFADAIQADAJAAAKIAAAFIg9AAIACAKQACAEADADIAHAGQAEABAFAAQAHAAAFgDQAGgFAGgJIAPAJIgIAMQgDAFgFADQgFADgGACQgGABgHAAQgKAAgIgDgAgMAQQgCgIgFgFQgGgDgIAAQgHAAgFADQgGAFgCAIIApAAIAAAAgAF9BIIAAgyQAAgMgDgGQgDgEgIAAQgEAAgDABQgEABgBADQgDADAAAGIgBAMIAAAuIgVAAIAAgyQAAgMgDgFQgEgFgHAAQgEAAgDABQgDABgCADQgCADgBAGIgBAMIAAAuIgUAAIAAhXIAUAAIAAAJQAGgHAEgCQAFgCAGAAQAIAAAGADQAGADAEAHQAFgHAGgDQAHgDAIAAQAIAAAFACQAGADADAEQAEAFACAFQACAGAAAJIAAA3gACDBIIAAgyQAAgNgEgFQgDgEgKAAQgFAAgEABQgDACgCADQgDAEgBAFIgBA5IgUAAIAAhXIAUAAIAAAJQAGgGAGgDQAFgCAHAAQAIAAAGACQAGADAEAEQAEAFACAEQACAHAAAKIAAA2gAAdBIIAAhXIAVAAIAABXgAiuBIIAAhGIgJAAIAAgRIAJAAIAAghIAUAAIAAAhIAQAAIAAARIgQAAIAABGgAjdBIIAAhXIAVAAIAABXgAAegqQgEgEAAgFQAAgGAEgEQAEgEAGAAQAFAAAEAEQAEAEAAAGQAAAFgEAEQgEAEgGgBQgFABgEgEgAjcgqQgEgEAAgFQAAgGAEgEQAEgEAGAAQAFAAAEAEQAEAEAAAGQAAAFgEAEQgEAEgGgBQgFABgEgEg");
	this.shape.setTransform(43.4,8.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(3.2,1,80.4,15.7);


(lib.button = function() {
	this.initialize();

	// Ebene 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AIxA2QgMgMAAgTQABgSAMgKQALgMASAAQATAAAKALQALAJAAATIAAAEIg/AAQABALAGAGQAGAGAKAAQAIAAAGgEQAGgDAEgIIAPAIQgGAMgKAGQgKAFgNAAQgTAAgLgLgAJBAAQgFAFgDAIIArAAQgBgIgFgEQgFgDgJAAQgKAAgFACgAEwA2QgLgMAAgTQAAgSALgKQAMgMASAAQATAAALALQAKAJAAATIAAAEIg+AAQAAALAGAGQAGAGAJAAQAKAAAFgEQAGgDAEgIIAQAIQgHAMgKAGQgKAFgNAAQgTAAgLgLgAFAAAQgFAFgCAIIArAAQgBgIgGgEQgFgDgKAAQgIAAgGACgABBA2QgMgMAAgTQABgSALgKQAMgMASAAQATAAAKALQALAJAAATIAAAEIg/AAQABALAGAGQAGAGAKAAQAIAAAGgEQAGgDAEgIIAPAIQgGAMgKAGQgKAFgNAAQgTAAgLgLgABRAAQgGAFgCAIIArAAQgBgIgFgEQgGgDgIAAQgKAAgFACgAjjA2QgMgMAAgTQAAgSAMgKQAMgMARAAQATAAALALQALAJgBATIAAAEIg+AAQABALAFAGQAHAGAJAAQAJAAAGgEQAFgDAFgIIAPAIQgHAMgJAGQgKAFgOAAQgTAAgKgLgAjUAAQgFAFgCAIIArAAQgBgIgFgEQgGgDgJAAQgJAAgGACgAqAA2QgMgMAAgTQAAgSAMgKQAMgMARAAQAUAAAKALQALAJAAATIAAAEIg/AAQABALAFAGQAHAGAJAAQAJAAAGgEQAFgDAFgIIAPAIQgHAMgJAGQgLAFgNAAQgSAAgLgLgApwAAQgGAFgCAIIArAAQgBgIgFgEQgGgDgJAAQgJAAgFACgArJA+QgGgDgGgGIANgNQACAEADABQADACADAAQAGAAADgEQACgDAAgLIAAhWIATAAIAABdQAAAPgGAHQgHAHgPAAQgHAAgHgDgALEA+IAAgoQgBgQgDgFQgEgDgJAAQgHAAgEACQgGABgCAEQgCADgBAEIgBAOIAAAkIgSAAIAAhMIARAAIAAAMQAFgIAIgDQAHgEALAAQAIAAAGADQAHACADAGIADAGIABAPIAAAvgAIBA+IAAgoQAAgQgDgFQgFgDgJAAQgHAAgEACQgFABgDAEQgCADAAAEIgBAOIAAAkIgSAAIAAhMIARAAIAAAMQAFgIAHgDQAHgEALAAQAJAAAGADQAGACAEAGIACAGIABAPIAAAvgAGJA+IAAhNIASAAIAAANQADgIAFgDQAEgEAIAAIAHABIAHACIgGAOIgFgBIgGgBQgJAAgEAGQgEAHAAARIAAAigAD/A+IAAh+IASAAIAAB+gADUA+IAAgoQAAgQgEgFQgEgDgJAAQgHAAgEACQgGABgCAEQgCADgBAEIgBAOIAAAkIgSAAIAAhMIARAAIAAAMQAFgIAIgDQAHgEALAAQAIAAAGADQAHACADAGIADAGIABAPIAAAvgAARA+IAAgoQAAgQgDgFQgFgDgJAAQgEAAgFACQgFABgDAEQgCADAAAEIgBAOIAAAkIgSAAIAAhMIARAAIAAAMQAFgIAHgDQAIgEAIAAQAJAAAGADQAGACAEAGIACAGIABAPIAAAvgAhRA+IAAgoQAAgQgDgFQgFgDgJAAQgGAAgFACQgFABgDAEQgCADAAAEIgBAOIAAAkIgSAAIAAhMIAQAAIAAAMQAGgIAHgDQAIgEAKAAQAJAAAGADQAGACAEAGIADAGIAAAPIAAAvgAkLA+IgkgoIAAAoIgSAAIAAh+IASAAIAABQIAhgeIAWAAIgjAgIAnAsgAmkA+IAAg+IgNAAIAAgOIANAAIAAgeIASAAIAAAeIAPAAIAAAOIgPAAIAAA+gAoBA+IAsg+IgoAAIAAgOIBFAAIgrA8IArAAIAAAQgAokA+IAAg+IgNAAIAAgOIANAAIAAgeIASAAIAAAeIAPAAIAAAOIgPAAIAAA+g");
	this.shape.setTransform(84.7,16.3);

	// Ebene 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#18684D").s().p("AtginIbAAUIhQEgI4dAbQhSlFgBgKg");
	this.shape_1.setTransform(86.5,16.9);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,173,33.8);


(lib.Blende_HG = function() {
	this.initialize();

	// Ebene 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("A6eV3MAAAgruMA09AAAMAAAArug");
	this.shape.setTransform(169.5,140);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,339,280);


(lib.stuhl_unten = function() {
	this.initialize();

	// Ebene 1
	this.instance = new lib.ClipGroup();
	this.instance.setTransform(57.7,-0.4,1,1,0,0,0,65.9,90);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D0D1D1").s().p("AgtCaIAAkzIBbAAIAAEzg");
	this.shape.setTransform(59.4,54.3);

	this.instance_1 = new lib.ClipGroup_1();
	this.instance_1.setTransform(57.7,-0.4,1,1,0,0,0,65.9,90);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#316B54").s().p("AG5gHIuqAxIg0grIBqh1IO/AgIAhCJIgfBBIhBACg");
	this.shape_1.setTransform(68.6,34);

	this.addChild(this.shape_1,this.instance_1,this.shape,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-8.2,-90.4,131.8,180);


(lib.Stuhl_front = function() {
	this.initialize();

	// Ebene 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C6C7C7").s().p("AhKA1IAAhpICVAAIAABpg");
	this.shape.setTransform(74.1,173.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#D0D1D1").s().p("Ag6CNIAAkZIB1AAIAAEZg");
	this.shape_1.setTransform(74,155.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#D0D1D1").s().p("AigAMIADgXIEAjEIA+AaIkCCyID/C5Ig+Aag");
	this.shape_2.setTransform(94.7,176);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#D0D1D1").s().p("AidC2ID/i5IkCizIA+gZIEBDDIACAYIkADEg");
	this.shape_3.setTransform(56.1,176.9);

	this.instance = new lib.ClipGroup_3();
	this.instance.setTransform(73.2,98.9,1,1,0,0,0,73.2,98.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#D0D1D1").s().p("AhhEYIgji5IDwmBIAZACIjWGHIAoB4IgFBEg");
	this.shape_4.setTransform(13.5,72.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#2B2B2A").ss(0.2,0,0,4).p("ABUBnIjXmHIAagDIDwGBIgkC6IgzALIgFhEg");
	this.shape_5.setTransform(132.7,72.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#D0D1D1").s().p("AApDfIAph4IjWmHIAZgCIDwGBIgjC5IgzALg");
	this.shape_6.setTransform(132.9,72.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#316B54").s().p("ApmDiIAGmLICIikIPCgGIB9DMIgRGAIgdBVIyIAGg");
	this.shape_7.setTransform(74.5,107);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#316B54").s().p("Amck5IAtgnILOgHIA2AuIA7KbIufAGg");
	this.shape_8.setTransform(73.7,36);

	this.instance_1 = new lib.ClipGroup_1_1();
	this.instance_1.setTransform(73.2,98.9,1,1,0,0,0,73.2,98.9);

	this.addChild(this.instance_1,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.instance,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,147.3,197.8);


// stage content:
(lib.chair_html5_336x280 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_329 = function() {
		this.stop();
		/*
		if(!this.alreadyExecuted){
		
		this.alreadyExecuted=true;
		
		this.loopNum=1;
		
		} else {
		
		this.loopNum++;
		
		if(this.loopNum==2){
		
		this.stop();
		
		}
		
		}
		*/
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(329).call(this.frame_329).wait(117));

	// Blende
	this.instance = new lib.Blende_HG();
	this.instance.setTransform(150.1,125,1,1,0,0,0,150,125);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(425).to({_off:false},0).to({alpha:1},16).wait(5));

	// Klassiker
	this.instance_1 = new lib.Klassiker_mc();
	this.instance_1.setTransform(176.9,148,1,1,0,0,0,54.9,21);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(245).to({_off:false},0).to({x:186.9,alpha:1},11).wait(53).to({x:196.9,alpha:0},10).to({_off:true},1).wait(126));

	// Claim
	this.instance_2 = new lib.endcopy_mc();
	this.instance_2.setTransform(168.9,160,1,1,0,0,0,54.9,21);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(319).to({_off:false},0).to({x:185.9,alpha:1},10).wait(117));

	// card
	this.instance_3 = new lib.card();
	this.instance_3.setTransform(68.2,125,0.739,0.697,0,0,0,51.1,33);
	this.instance_3.alpha = 0.09;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(245).to({_off:false},0).to({regX:51,scaleX:1,scaleY:1,x:65,y:142,alpha:1},11,cjs.Ease.get(1)).wait(190));

	// CTA
	this.instance_4 = new lib.button();
	this.instance_4.setTransform(197.5,208.1,1,1,0,0,0,86.5,16.9);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(319).to({_off:false},0).to({alpha:1},10,cjs.Ease.get(1)).wait(117));

	// Ebene 6
	this.instance_5 = new lib.PNG_Logo();
	this.instance_5.setTransform(256,38.5,1,1,0,0,0,24,20.5);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(256).to({_off:false},0).to({alpha:1},10).wait(180));

	// Ebene 8
	this.instance_6 = new lib.C4_1();
	this.instance_6.setTransform(218.8,53.1,1,1,15,0,0,43.4,12.6);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(155).to({_off:false},0).to({regX:43.5,regY:12.1,scaleX:1,scaleY:1,rotation:9.8,guide:{path:[218.7,52.9,210.3,67.7,206.4,84.3]},alpha:1},15).wait(63).to({regY:12,x:206.5,y:84.2},0).to({guide:{path:[206.4,84.2,206.4,84.2,206.4,84.2]},alpha:0},11).wait(202));

	// Ebene 9
	this.instance_7 = new lib.C4_2();
	this.instance_7.setTransform(215.1,60,1,1,15.2,0,0,79.4,12.2);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(157).to({_off:false},0).to({regX:79.2,regY:12.5,rotation:0,guide:{path:[215.1,59.9,203,84.9,203,115,203,116.4,203,117.8]},alpha:1},13).wait(63).to({alpha:0},11).wait(202));

	// Ebene 10
	this.instance_8 = new lib.C4_3();
	this.instance_8.setTransform(212.7,65.4,1,1,14.7,0,0,72.5,12.6);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(159).to({_off:false},0).to({regX:72.2,regY:12.1,rotation:-7.1,guide:{path:[212.7,65.5,203,88.1,203,114.9,203,134.4,208.1,151.8]},alpha:1},11).wait(63).to({rotation:-7.1,x:208.2,y:151.9},0).to({guide:{path:[208.1,151.8,208.1,151.8,208,151.8]},alpha:0},11).wait(202));

	// Ebene 1
	this.instance_9 = new lib.Stuhl_front();
	this.instance_9.setTransform(70.4,133.8,0.289,0.289,0,0,0,73.1,98.9);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(142).to({_off:false},0).to({regX:73.2,scaleX:0.7,scaleY:0.7,x:68.6,y:118,alpha:1},17,cjs.Ease.get(1)).wait(74).to({alpha:0},11).wait(202));

	// Ebene 13
	this.instance_10 = new lib.nnter("synched",0);
	this.instance_10.setTransform(201.8,146.3);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(93).to({_off:false},0).to({alpha:1},7).to({x:179.8},9,cjs.Ease.get(1)).wait(23).to({startPosition:0},0).to({alpha:0},12).wait(302));

	// copy_03
	this.instance_11 = new lib.entspa();
	this.instance_11.setTransform(151.8,146.5,1,1,81.2,0,0,97.2,20.8);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(93).to({_off:false},0).to({alpha:1},7).to({regX:97.4,rotation:54.3,x:134.4,y:146.6},9,cjs.Ease.get(1)).wait(23).to({alpha:0},12).wait(302));

	// copy_02
	this.instance_12 = new lib.copy_02_mc();
	this.instance_12.setTransform(86.3,35.5,1,1,0,0,0,81.3,13.5);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(45).to({_off:false},0).to({x:96.3,alpha:1},11,cjs.Ease.get(1)).wait(25).to({x:106.3,alpha:0},16,cjs.Ease.get(1)).wait(349));

	// Copy_01
	this.instance_13 = new lib.copy_01_mc();
	this.instance_13.setTransform(103.4,35.5,1,1,0,0,0,98.4,13.5);
	this.instance_13.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).to({x:113.4,alpha:1},10,cjs.Ease.get(1)).wait(24).to({x:123.4,alpha:0},11,cjs.Ease.get(1)).wait(401));

	// stuhl
	this.instance_14 = new lib.ClipGroup();
	this.instance_14.setTransform(187,150.5,1,1,0,0,0,65.9,90);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D0D1D1").s().p("AgtCaIAAkzIBbAAIAAEzg");
	this.shape.setTransform(188.7,205.2);

	this.instance_15 = new lib.ClipGroup_1();
	this.instance_15.setTransform(187,150.5,1,1,0,0,0,65.9,90);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#316B54").s().p("AG5gHIuqAxIg0grIBqh1IO/AgIAhCJIgfBBIhBACg");
	this.shape_1.setTransform(197.9,184.9);

	this.instance_16 = new lib.stuhl_unten();
	this.instance_16.setTransform(187,150.5,1,1,0,0,0,57.7,-0.4);
	this.instance_16._off = true;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.instance_15},{t:this.shape},{t:this.instance_14}]}).to({state:[{t:this.shape_1},{t:this.instance_15},{t:this.shape},{t:this.instance_14}]},109).to({state:[{t:this.instance_16}]},23).to({state:[{t:this.instance_16}]},12).wait(302));
	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(132).to({_off:false},0).to({alpha:0},12).wait(302));

	// Lehne
	this.instance_17 = new lib.ClipGroup_2();
	this.instance_17.setTransform(151.7,180.7,1,1,0,0,0,30.6,120.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(100).to({regX:30.7,regY:120.1,rotation:-26.7,x:151.8,y:180.6},9,cjs.Ease.get(1)).wait(23).to({alpha:0},12).wait(302));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(176.9,158.8,244,221.7);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;