/*

 @version 0.9.22
 @authors Margaret Fudali, Andre Charbonneau
 @copyright © 2015 National Research Council of Canada.  All rights reserved.           

 Disclaimer:
 This software is supplied "as is". Her Majesty the Queen in Right of Canada 
 as represented by the Minister of Industry (“Canada”) makes no 
 representations or warranties, express or implied, of any kind whatsoever, 
 and assumes no liability for the accuracy, completeness, or usefulness of 
 the software. Canada does not assume any liability in respect of any damages 
 or losses arising out of or in connection with the use, or inability to use, 
 the software. 
 For the complete complete list of terms and conditions for NRC's web site,
 please refer to http://www.nrc-cnrc.gc.ca/eng/notices/index.html.

 Avertissement :
 Ce logiciel est fourni « tel quel ». Sa Majesté la reine du chef du Canada, 
 représentée par le Ministre de l’Industrie (« Canada» ) ne fait aucune 
 représentation ni ne donne aucune garantie, expresse ou implicite de quelque 
 nature que ce soit et n’assume aucune responsabilité concernant l’exactitude, 
 l’exhaustivité ou l’utilité du logiciel.   Le Canada n’assume aucune 
 responsabilité vis-à-vis des dommages ou pertes résultant de l’utilisation 
 ou de l’impossibilité d’utilisation du logiciel.  
 Pour obtenir une liste complète des termes et conditions du site Web du 
 CNRC, visitez http://zone.nrc-cnrc.gc.ca/notices_f.html

*/
var this_app_version="version 0.9.22",debug_mode=!1,stratum_query_interval_length=3E4,clock_repaint_interval_length=1E3,num_of_stratum_query_retries=5,stratum_query_retry_count=0,stratum_2_base_url="http://time5.nrc-cnrc.gc.ca/cgi-bin/get_ts2",offset=null,round_trip_delay_ms=null,one_way_delay=null,timeRequest=null,response_received_ts=null,isIE=window.XDomainRequest?!0:!1,time_to_display=null,clock_repaint_interval=null,stratum_query_interval=null,the_language=$("html").attr("lang"),clock_mode=null,
timezone_names="Canada/Pacific Canada/Mountain Canada/Central Canada/Eastern Canada/Atlantic Canada/Newfoundland UTC".split(" "),tz="UTC",display_formats={"12hr":"hh:mm:ss A","24hr":"HH:mm:ss"},display_format=display_formats["12hr"],translation_map={PST:{en:"PST",fr:"HNP"},MST:{en:"MST",fr:"HNR"},CST:{en:"CST",fr:"HNC"},EST:{en:"EST",fr:"HNE"},AST:{en:"AST",fr:"HNA"},NST:{en:"NST",fr:"HNT"},PDT:{en:"PDT",fr:"HAP"},MDT:{en:"MDT",fr:"HAR"},CDT:{en:"CDT",fr:"HAC"},EDT:{en:"EDT",fr:"HAE"},ADT:{en:"ADT",
fr:"HAA"},NDT:{en:"NDT",fr:"HAT"},UTC:{en:"UTC",fr:"UTC"},"Loading...":{en:"Loading...",fr:"Chargement en cours..."},"NRC official time":{en:"NRC official time",fr:"Heure officielle du CNRC"},"Select clock":{en:"Select clock",fr:"Choisir l'horloge"},"Select time zone":{en:"Select time zone",fr:"Choisir le fuseau horaire"},"Your local clock is ":{en:"Your local clock is ",fr:"L'horloge locale a "},"Your local clock is less than 0.01 seconds slow.":{en:"Your local clock is less than 0.01 second slow.",
fr:"L'horloge locale a moins de 0,01 seconde de retard. "},"Your local clock is less than 0.01 seconds fast.":{en:"Your local clock is less than 0.01 second fast.",fr:"L'horloge locale a moins de 0,01 seconde d'avance. "}," seconds slow.":{en:" seconds slow.",fr:" secondes de retard."}," seconds fast.":{en:" seconds fast.",fr:" secondes d'avance."},"Learn more / Settings":{en:"Learn more / Settings",fr:"En savoir plus / Paramètres"},"12hr":{en:"12 hr",fr:"12 hr"},"24hr":{en:"24 hr",fr:"24 hr"},"Estimated network delay is ":{en:"Estimated network delay is ",
fr:"Retard du temps de réseau estimé à "},"Estimated network delay is less than 0.01 seconds.":{en:"Estimated network delay is less than 0.01 second.",fr:"Retard du temps de réseau estimé à moins de 0,01 seconde. "}," seconds.":{en:" seconds.",fr:" secondes."},"Stratum 2 query error":{en:"Error",fr:"Erreur"},"An error occurred when communicating with the NRC time server.":{en:"An error occurred when communicating with the NRC time server.",fr:"Une erreur s'est produite lors de la communication avec le serveur de temps."}},
tz_abbr_map={PST:"Pacific Standard Time",MST:"Mountain Standard Time",CST:"Central Standard Time",EST:"Eastern Standard Time",AST:"Atlantic Standard Time",NST:"Newfoundland Standard Time",PDT:"Pacific Daylight Time",MDT:"Mountain Daylight Time",CDT:"Central Daylight Time",EDT:"Eastern Daylight Time",ADT:"Atlantic Daylight Time",NDT:"Newfoundland Daylight Time",HNP:"Heure normale du Pacifique",HNR:"Heure normale des Rocheuses",HNC:"Heure normale du Centre",HNE:"Heure normale de l’Est",HNA:"Heure normale de l’Atlantique",
HNT:"Heure normale de Terre-Neuve",HAP:"Heure avancée du Pacifique",HAR:"Heure avancée des Rocheuses",HAC:"Heure avancée du Centre",HAE:"Heure avancée de l’Est",HAA:"Heure avancée de l’Atlantique",HAT:"Heure avancée de Terre-Neuve"};function getStr(a){return a in translation_map?translation_map[a][the_language]:a}function getNonAbbrTimezone(a){return"UTC"==a?"fr"==the_language?"Temps universel coordonné":"Coordinated Universal Time":a in tz_abbr_map?tz_abbr_map[a]:a}
function initClock(){clock_mode=$("#nrc_clock").attr("clock_mode");"fr"==the_language&&(display_format=display_formats["24hr"]);tz=getCurrentTz();var a=new Date;$("#nrc_clock_version_label").length&&$("#nrc_clock_version_label").text(getVersion());$("#h2_clock_label").text(getStr("NRC official time"));$("#h3_clock_label1").text(getStr("Select clock"));$("#h3_clock_label2").text(getStr("Select time zone"));$("#info_button").text(getStr("Learn more / Settings"));if("tabbed"==clock_mode)for(var b=0;7>
b;b++){$("#tzpanel-"+(b+1)).css({outline:"none"});var c="#tztab-"+(b+1),d=getStr(moment.tz(a,timezone_names[b]).zoneAbbr()),e=getNonAbbrTimezone(d);$(c).html('<abbr title="'+e+'">'+d+"</abbr>");$(c).attr("name",timezone_names[b]);$("#timeDiv"+(b+1)).text(getStr("Loading...."));$("#tzDiv"+(b+1)).text(d);$("#uncDiv"+(b+1)).text(getStr("Loading...."));$("#displayFormat12hr").text(getStr("12hr"));$("#displayFormat24hr").text(getStr("24hr"));$("#displayFormat12hr").click(function(){displayFormatClicked(display_formats["12hr"])});
$("#displayFormat24hr").click(function(){displayFormatClicked(display_formats["24hr"])});selectTzTab(tz)}else d=getStr(moment.tz(a,tz).zoneAbbr()),$("#timeDiv1").text(getStr("Loading....")),$("#tzDiv1").text(d),$("#uncDiv1").text(getStr("Loading...."));clock_repaint_interval=setInterval(repaintClock,clock_repaint_interval_length);stratum_query_interval=setInterval(getTimeFromStratum,stratum_query_interval_length);setTimeout(getTimeFromStratum,0)}
function selectTzTab(a){for(var b=0;7>b;b++){var c="#tztab-"+(b+1);if($(c).attr("name")==a){$(c).trigger("click");$(c).trigger("expand");break}}}function displayFormatClicked(a){display_format=a;repaintClock(!0)}function getCurrentTz(){for(var a=new Date,b="UTC",c=0;c<timezone_names.length;c++)if(z=moment.tz.zone(timezone_names[c]),z.offset(a.getTime())==a.getTimezoneOffset()){b=timezone_names[c];break}return b}function hasTzChanged(){return tz!=getCurrentTz()}
function log(a){debug_mode&&console.log(a)}
function setRepaintIntervalIn(a){0>a?log("Negative argument given to setRepaintIntervalIn; discarding."):(1E3<a&&log("WARNING: Argument given to setRepaintIntervalIn is > 1000."),null!=clock_repaint_interval&&(clearInterval(clock_repaint_interval),clock_repaint_interval=null),0==a?(log("Setting new repaint interval to start NOW."),clock_repaint_interval=setInterval(repaintClock,1E3),repaintClock()):(log("Scheduling new repaint intervals to start in "+a+"ms."),setTimeout("setRepaintIntervalIn(0)",
a)))}
function repaintClock(a){if(stratum_query_retry_count>=num_of_stratum_query_retries)setClockToStratumQueryError();else if(hasTzChanged())tz=getCurrentTz(),"tabbed"==clock_mode&&selectTzTab(tz);else if(null!=offset){var b=time_to_display;time_to_display=new Date((new Date).getTime()+offset);if(void 0===a&&null!=b&&Math.floor(b.getTime()/1E3)==Math.floor(time_to_display.getTime()/1E3))log("Same time display detected!  Readjusting repaint interval accordingly."),setRepaintIntervalIn(1E3-time_to_display.getMilliseconds());else if(a=
Math.abs(offset/1E3).toFixed(2),b=Math.abs(one_way_delay/1E3).toFixed(2),"tabbed"==clock_mode)for(var c=0;7>c;c++){var d=moment.tz(time_to_display,timezone_names[c]).format(display_format),e=moment.tz(time_to_display,timezone_names[c]).format("Z");$("#tzoffDiv"+(c+1)).text(getStr("(UTC")+e+")");$("#timeDiv"+(c+1)).text(d);0==a?0<offset?$("#uncDiv"+(c+1)).text(getStr("Your local clock is less than 0.01 seconds slow.")):0>offset&&$("#uncDiv"+(c+1)).text(getStr("Your local clock is less than 0.01 seconds fast.")):
0<offset?$("#uncDiv"+(c+1)).text(getStr("Your local clock is ")+a+getStr(" seconds slow.")):$("#uncDiv"+(c+1)).text(getStr("Your local clock is ")+a+getStr(" seconds fast."));0==b?$("#delDiv"+(c+1)).text(getStr("Estimated network delay is less than 0.01 seconds.")):$("#delDiv"+(c+1)).text(getStr("Estimated network delay is ")+b+getStr(" seconds."))}else b=getStr(moment.tz(time_to_display,tz).zoneAbbr()),$("#tzDiv1").text(b),e=moment.parseZone(time_to_display).format("Z"),$("#tzoffDiv1").text(getStr("(UTC")+
e+")"),d=moment.tz(time_to_display,tz).format(display_format),$("#timeDiv1").text(d),0==a?0<offset?$("#uncDiv1").text(getStr("Your local clock is less than 0.01 seconds slow.")):0>offset&&$("#uncDiv1").text(getStr("Your local clock is less than 0.01 seconds fast.")):0<offset?$("#uncDiv1").text(getStr("Your local clock is ")+a+getStr(" seconds slow.")):$("#uncDiv1").text(getStr("Your local clock is ")+a+getStr(" seconds fast."))}}
function setClockToStratumQueryError(){if("tabbed"==clock_mode)for(var a=0;7>a;a++)$("#timeDiv"+(a+1)).text(""),$("#uncDiv"+(a+1)).text(getStr("An error occurred when communicating with the NRC time server.")),$("#delDiv"+(a+1)).text(""),$("#tzDiv"+(a+1)).text(""),$("#tzoffDiv"+(a+1)).text("");else $("#timeDiv1").text(""),$("#uncDiv1").text(getStr("An error occurred when communicating with the NRC time server.")),$("#tzDiv1").text(""),$("#tzoffDiv1").text("")}
function createCrossDomainRequest(){return isIE?new window.XDomainRequest:new XMLHttpRequest}
function getTimeFromStratum(){timeRequest=createCrossDomainRequest();var a=stratum_2_base_url;isIE?(timeRequest.timeout=1E3,timeRequest.open("GET",a+"?original="+(new Date).getTime(),!0),timeRequest.onload=function(){response_received_ts=(new Date).getTime();processStratum2Response(timeRequest.responseText)},timeRequest.ontimeout=function(){log("Cross Domain Request Error (IE). Reason: timeout");stratum_query_retry_count++},timeRequest.onerror=function(){log("Cross Domain Request Error (IE). Reason: unable to complete the request.");
stratum_query_retry_count++}):(timeRequest.open("GET",a+"?original="+(new Date).getTime(),!0),timeRequest.onreadystatechange=function(){response_received_ts=(new Date).getTime();4==timeRequest.readyState&&200==timeRequest.status&&processStratum2Response(timeRequest.responseText)},timeRequest.ontimeout=function(){log("Cross Domain Request Error. Reason: timeout");stratum_query_retry_count++},timeRequest.onerror=function(){log("Cross Domain Request Error. Reason: unable to complete the request.");stratum_query_retry_count++});
timeRequest.send()}function processStratum2Response(a){log(a);if("ERR"!=a){var b=a.split("|");a=Number(b[0]);var c=Number(b[1]),b=Number(b[2]),d=response_received_ts;offset=(c-a+(b-d))/2;round_trip_delay_ms=d-a-(b-c);one_way_delay=round_trip_delay_ms/2;stratum_query_retry_count=0;setRepaintIntervalIn(1E3-(new Date((new Date).getTime()+offset)).getMilliseconds())}}function getVersion(){return this_app_version};
